# Site settings
title: Younes General Trading
email: info@younesgeneraltrading.com
description: "Your Partner in Seamless International Trade."
baseurl: "/younes.github.io"
url: "https://selimyo.github.io"

# Theme settings
remote_theme: daattali/beautiful-jekyll@6.0.1
avatar: "/assets/img/logo.png"
round-avatar: true
hero_image: "/assets/img/toronto-skyline-james-wheeler.jpg"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Plugins - Only include necessary plugins for beautiful-jekyll and remote_theme
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

social-network-links:
  email: "info@younesgeneraltrading.com"
